name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      working-directory: ./devops-ci-challenge/codebase/rdicidr-0.1.0
      run: npm install
      
    - name: Linter (ESLint)
      working-directory: ./devops-ci-challenge/codebase/rdicidr-0.1.0
      run: npm run lint
      
    - name: Formatter (Prettier)
      working-directory: ./devops-ci-challenge/codebase/rdicidr-0.1.0
      run: npm run prettier
      
    - name: Test (Jest)
      working-directory: ./devops-ci-challenge/codebase/rdicidr-0.1.0
      env:
        CI: true
      run: npm run test
      
    - name: Build
      working-directory: ./devops-ci-challenge/codebase/rdicidr-0.1.0
      run: npm run build
